---
title: "2020-03-04"
output: github_document
---

# `tidyr::drop_na()` - i know this one!

```{r old, echo = TRUE}
library(tidyr)

df <- tribble(
  ~date,        ~fruit,   ~cost, ~sales,
  "2020-03-01", "Apple",     NA,     NA,
  "2020-03-01", "Banana",     5,      3,
  "2020-03-02", "Apple",     10,      4,
  "2020-03-02", "Banana",    NA,      1
)

# Use drop_na() to drop any records where a variable is NA
# By default, drops records where *any* variable has NA:
df %>%
  drop_na()

# Specify a variable to only drop if that variable is NA:
df %>%
  drop_na(sales)

# Use tidyselect, too!
df %>%
  drop_na(starts_with("dat"))
```

# `magrittr::set_colnames()` - new to me!

```{r new, echo = TRUE, message = FALSE}
library(magrittr)
library(dplyr)
library(knitr)

df <- tribble(
  ~date,        ~fruit,   ~cost, ~sales,
  "2020-03-01", "Apple",     NA,     NA,
  "2020-03-01", "Banana",     5,      3,
  "2020-03-02", "Apple",     10,      4,
  "2020-03-02", "Banana",    NA,      1
)

# Change a data frame's column names within a pipeline!
df %>%
  group_by(date) %>%
  summarise(sales = sum(sales, na.rm = TRUE)) %>%
  set_colnames(c("Date", "Total Sales")) %>% # Hello! Right here!
  kable()

# No more of this!
df_sales <- df %>%
  group_by(date) %>%
  summarise(sales = sum(sales, na.rm = TRUE))

# Naming outside the pipeline! Yuck!
names(df_sales) <- c("Date", "Total Sales")

kable(df_sales)
```
