---
title: "2020-03-08"
output: github_document
---

# `lubridate::dst()` - i know this one!

```{r old, echo = TRUE, message = FALSE}
library(lubridate)

# Use dst() to check whether a date is during daylight savings
dst(ymd("2020-03-09", tz = "America/Toronto"))
dst(ymd("2020-03-07", tz = "America/Toronto"))

# What about the date it changes?
# The date is treated as midnight, which isn't daylight savings time yet. 
dst(ymd("2020-03-08", tz = "America/Toronto"))

# Use a datetime for more precision
dst(ymd_hms("2020-03-08 01:00:00", tz = "America/Toronto"))
dst(ymd_hms("2020-03-08 03:00:00", tz = "America/Toronto"))

# And if the time doesn't exist, you'll get an unknown:
dst(ymd_hms("2020-03-08 02:00:00", tz = "America/Toronto"))

# Of course, this is timezone dependent - not everywhere has daylight savings!
dst(ymd("2020-03-07", tz = "America/Phoenix"))
dst(ymd("2020-03-09", tz = "America/Phoenix"))
```

# `lubridate::dhours()` - new to me!

```{r new, echo = TRUE}
library(lubridate)

d <- ymd_hms("2020-03-08 00:00:00", tz = "America/Toronto")

# You can add time to a datetime with hours:
d + hours(1)

# But if you just try to add hours to a date that crosses over daylight savings, it won't work as expected:
d + hours(2)

# 2am on 2020-03-08 doesn't happen because of daylight savings - it skips right to 3am

# And technically, this is wrong, because 3 hours after midnight on the date of daylight savings should be 4am
d + hours(3)

# Use dhours() to add time in a way that is consistent with daylight savings:
d + dhours(2)
d + dhours(3)

# The respective functins for weeks, days, minutes, seconds exist too
ymd_hms("2020-03-07 02:25:00", tz = "America/Toronto") +
  ddays(1)

ymd_hms("2020-03-08 01:59:20", tz = "America/Toronto") +
  dminutes(1)
```
