---
title: "2020-05-14"
output: github_document
---

# `gt::tab_footnote()` - i know this one!

```{r old, echo = TRUE, warning = FALSE}
library(gt)
library(tibble)

acnh_bugs_n <- tribble(
  ~name, ~price, ~location, ~time, ~months,
  "Yellow butterfly", 160, "Flying", "4 AM - 7 PM", "Mar - Jun, Sep - Oct",
  "Peacock butterfly", 2500, "Flying by Hybrid Flowers", "4 AM - 7 PM", "Mar - June",
  "Atlas moth", 3000, "On Trees", "7 PM - 4 AM", "Apr - Sep",
  "Centipede", 300, "Hitting Rocks", "4 PM - 11 PM", "Sep - June",
  "Snail", 250, "On Rocks and Bushes (Rain)	", "All Day", "Jan - Dec",
  "Mole cricket", 500, "Underground", "All Day", "Nov - May"
)

# Add a footnote using tab_footnote()
# Specify it's a column label footnote via cells_column_labels
acnh_bugs_n %>%
  gt() %>%
  tab_footnote(
    footnote = "Price is in Bells",
    locations = cells_column_labels(columns = vars(price))
  )

# You can add a footnote to individual cells, too! Add to the body via cells_body()
# You can target specific rows with an expression that evaluates to TRUE (here, it's targetting any rows where the name is "Mole cricket"
acnh_bugs_n %>%
  gt() %>%
  tab_footnote(
    footnote = "Don't worry, you'll hear it. Dig!",
    locations = cells_body(
      columns = vars(location),
      rows = name == "Mole cricket"
    )
  )
```

# `gt::opt_footnote_marks()` - new to me!

```{r new, echo = TRUE}
library(gt)
library(tibble)

acnh_bugs_n <- tribble(
  ~name, ~price, ~location, ~time, ~months,
  "Yellow butterfly", 160, "Flying", "4 AM - 7 PM", "Mar - Jun, Sep - Oct",
  "Peacock butterfly", 2500, "Flying by Hybrid Flowers", "4 AM - 7 PM", "Mar - June",
  "Atlas moth", 3000, "On Trees", "7 PM - 4 AM", "Apr - Sep",
  "Centipede", 300, "Hitting Rocks", "4 PM - 11 PM", "Sep - June",
  "Snail", 250, "On Rocks and Bushes (Rain)	", "All Day", "Jan - Dec",
  "Mole cricket", 500, "Underground", "All Day", "Nov - May"
)

# If you don't like the default footnote formatting, you can change it with opt_footnote_marks()
acnh_bugs_n %>%
  gt() %>%
  tab_footnote(
    footnote = "Price is in Bells",
    locations = cells_column_labels(columns = vars(price))
  ) %>%
  opt_footnote_marks(marks = "standard")
```
