---
title: "2020-05-14"
output: github_document
---

# `gt::tab_source_note()` - i know this one!

```{r old, echo = TRUE, warning = FALSE}
library(gt)
library(tibble)

acnh_bugs_n <- tribble(
  ~name, ~price, ~location, ~time, ~months,
  "Yellow butterfly", 160, "Flying", "4 AM - 7 PM", "Mar - Jun, Sep - Oct",
  "Peacock butterfly", 2500, "Flying by Hybrid Flowers", "4 AM - 7 PM", "Mar - June",
  "Atlas moth", 3000, "On Trees", "7 PM - 4 AM", "Apr - Sep",
  "Centipede", 300, "Hitting Rocks", "4 PM - 11 PM", "Sep - June",
  "Snail", 250, "On Rocks and Bushes (Rain)	", "All Day", "Jan - Dec",
  "Mole cricket", 500, "Underground", "All Day", "Nov - May"
)

# Add a note to the bottom of the table (e.g., on the source) with tab_source_note()
gt(acnh_bugs_n) %>%
  gt::tab_source_note("Source: https://github.com/chendaniely/animalcrossing")
```

# `gt::md()` - new to me!

```{r new, echo = TRUE}
library(gt)
library(tibble)

acnh_bugs_n <- tribble(
  ~name, ~price, ~location, ~time, ~months,
  "Yellow butterfly", 160, "Flying", "4 AM - 7 PM", "Mar - Jun, Sep - Oct",
  "Peacock butterfly", 2500, "Flying by Hybrid Flowers", "4 AM - 7 PM", "Mar - June",
  "Atlas moth", 3000, "On Trees", "7 PM - 4 AM", "Apr - Sep",
  "Centipede", 300, "Hitting Rocks", "4 PM - 11 PM", "Sep - June",
  "Snail", 250, "On Rocks and Bushes (Rain)	", "All Day", "Jan - Dec",
  "Mole cricket", 500, "Underground", "All Day", "Nov - May"
)

# Use markdown with md()!
gt(acnh_bugs_n) %>%
  tab_source_note(md("Source: Daniel Chen's [{animalcrossing} package](https://github.com/chendaniely/animalcrossing)"))

# You can use it anywhere, not just in the source note!
gt(acnh_bugs_n) %>%
  tab_header(title = md("*Animal Crossing New Horizons* Critters"))
```
