---
title: "2020-03-27"
output: github_document
---

# `forcats::fct_reorder()` - i know this one!

```{r old, echo = TRUE, message = FALSE}
library(forcats)
library(dplyr)

nintendo <- tribble(
  ~console, ~hardware_sales_million,
  "Nintendo Switch", 52.48,
  "Nintendo 3DS", 75.71,
  "Wii U", 13.56,
  "Wii", 101.63,
  "Nintendo DS", 154.02,
  "Game Boy Advance", 81.51,
  "Game Boy", 118.69,
  "Nintendo GameCube", 21.74,
  "Nintendo 64", 32.93,
  "SNES", 49.10,
  "NES", 61.91
)

# Use fct_reorder() to reorder levels based on a variable
nintendo %>%
  mutate(console = fct_reorder(console, hardware_sales_million)) %>%
  pull(console) %>%
  levels()

# The default is ascending order, so set to descending if you want!
nintendo %>%
  mutate(console = fct_reorder(console, hardware_sales_million, .desc = TRUE)) %>%
  pull(console) %>%
  levels()
```

# `forcats::fct_lump_*()` - new to me!

```{r new, echo = TRUE}
library(forcats)
library(dplyr)

nintendo <- tribble(
  ~console, ~hardware_sales_million,
  "Nintendo Switch", 52.48,
  "Nintendo 3DS", 75.71,
  "Wii U", 13.56,
  "Wii", 101.63,
  "Nintendo DS", 154.02,
  "Game Boy Advance", 81.51,
  "Game Boy", 118.69,
  "Nintendo GameCube", 21.74,
  "Nintendo 64", 32.93,
  "SNES", 49.10,
  "NES", 61.91
)

# Use fct_lump_n() to lump together everything except the top 5
# Supply w (weight) because the frequency is pre-aggregated
nintendo %>%
  mutate(console = fct_lump_n(console, n = 5, w = hardware_sales_million))

# Use fct_lump_min() to lump together everything that sold less than 50 million units
# Rename the other level via "other_level"
nintendo %>%
  mutate(console = fct_lump_min(console, min = 50, w = hardware_sales_million, other_level = "Other Consoles"))

# Use fct_lump_prop() to lump together everything that is less than 10% of total sales 
nintendo %>%
  mutate(console = fct_lump_prop(console, prop = 0.20, w = hardware_sales_million))
```
