---
title: "2020-04-21"
output: github_document
always_allow_html: true
---

# `kableExtra::column_spec()` - i know this one!

```{r old, echo = TRUE}
library(kableExtra)
library(tibble)

nintendo_sales <- tribble(
  ~console, ~hardware_sales, ~software_sales,
  "Nintendo Switch", 52.48, 310.65,
  "Wii", 101.63, 921.41,
  "Nintendo DS", 154.02, 948.69,
  "Game Boy", 118.69, 501.11,
  "Nintendo 64", 32.93, 224.97,
  "SNES", 49.1, 379.06,
  "Other Consoles", 254.43, 1571.23
)

k <- nintendo_sales %>%
  kable(col.names = c("Console", "Hardware", "Software"))

# Use column_spec() to alter the appearance of a column!
k %>%
  column_spec(
    column = 1,
    italic = TRUE
  )

# Excludes the header by default, but you can set it to include it with `include_thread`!
# Specify multiple columns, too!
k %>%
  column_spec(
    column = 2:3,
    italic = TRUE,
    include_thead = TRUE
  )
```

# `kableExtra::collapse_rows()` - new to me!

```{r new, echo = TRUE, warning = FALSE, message = FALSE}
library(kableExtra)
library(tibble)

nintendo_sales <- tribble(
  ~console, ~sales_type, ~sales_million,
  "Nintendo Switch", "Hardware", 52.48,
  "Nintendo Switch", "Software", 310.65,
  "Game Boy", "Hardware", 118.69,
  "Game Boy", "Software", 501.11,
  "Nintendo 64", "Hardware", 32.93,
  "Nintendo 64", "Software", 224.97,
  "SNES", "Hardware", 49.1,
  "SNES", "Software", 379.06,
)

# You might have information in your data that doesn't need to be repeated
# You can collapse values from a column into a single row:
nintendo_sales %>%
  kable(col.names = c("Console", "Type", "Sales")) %>%
  collapse_rows(columns = 1)

# Positions the row in the middle by default, but you can change that!
nintendo_sales %>%
  kable(col.names = c("Console", "Type", "Sales")) %>%
  collapse_rows(
    columns = 1,
    valign = "top"
  )
```
